services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: saude-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"   # troque aqui
      MSSQL_PID: "Developer"
    volumes:
      - ./sql:/sql:ro
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  mssql_data:
